### ISSUE TITLE
Error when calculating with very winning odds. 

### ISSUE THREAD

**Issue by GAMPR** [elleklinton/PiedPoker#3]
How are you elleklinton? I would like to start by saying that this program is insane. And a work of art. Exactly what I was looking for. I would like to alert you of an error I have found when you give it ridiculous odds because it is attempting to divide by 0 somewhere. Such as when the player as a 4 of a king of Aces, I would guess the odds of winning are becoming ridiculous by then since the only things that can beat it are a royal flush or a straight flush. Here is the exact error it gives. A simple try catch block could fix this, I don't see the point in giving mathematical values by then. Maybe a text block alerting that gives any specific superior hands if they exist, or if they don't to give 100% odds. Thank you for you program, have a nice day. 

`Traceback (most recent call last):
  File "/home/trdat/Reese/Real projects/pogger/New.py", line 21, in <module>
    print(simulation_result.probability_of(pp.PlayerWins(p1)))
  File "/home/trdat/.local/share/virtualenvs/pogger-a1Yavf9e/lib/python3.10/site-packages/pied_poker/probability/probability_value.py", line 26, in __str__
    return self.__repr__()
  File "/home/trdat/.local/share/virtualenvs/pogger-a1Yavf9e/lib/python3.10/site-packages/pied_poker/probability/probability_value.py", line 29, in __repr__
    return f'{self.__percent_str__} == {self.__odds_str__} == ({self.__ratio_str__})'
  File "/home/trdat/.local/share/virtualenvs/pogger-a1Yavf9e/lib/python3.10/site-packages/pied_poker/probability/probability_value.py", line 18, in __odds_str__
    return f'{round(1/r, 2)}:1 odds'
ZeroDivisionError: float division by zero`

Here's the exact code that gave this error:

`import pied_poker as pp
import numpy as np
np.random.seed(420)

p1 = pp.Player('Ellek', pp.Card.of('as', 'ad'))
p2 = pp.Player('Opp1')
p3 = pp.Player('Opp2') 
p4 = pp.Player('Opp3') 
print(p1, p2, p3, p4)

community_cards = pp.Card.of('9c', '8h', 'ac', '7s', 'ah') 
print(community_cards) 

simulator = pp.PokerRoundSimulator(community_cards=community_cards, 
                       players=[p1, p2],
                      total_players=2)
num_simulations = 10000

simulation_result = simulator.simulate(n=num_simulations, n_jobs=1)

print(simulation_result.probability_of(pp.PlayerWins(p1))) 
print(simulation_result.probability_of(pp.PlayerWins(p2))) 
#print(simulation_result.probability_of(pp.PlayerWins(p3))) 
#print(simulation_result.probability_of(pp.PlayerWins(p4))) 

#simulation_result.visualize_player_hand_distribution(p1)
#simulation_result.visualize_player_hand_distribution(p2)
#simulation_result.visualize_player_hand_distribution(p3)
#simulation_result.visualize_player_hand_distribution(p4)`

**Comment by GAMPR** [comment]
I just redid it, and it seems to be exactly for 100% odds, try catch should just return the 100% value. Lol.

**Comment by GAMPR** [comment]
This seems to have fixed it on my computer. If anyone else gets this error its just this in probability_value.py:
`        if r < 1:
            if r < 0.0000001: 
                return r
            else: 
                return f'{round(1/r, 2)}:1 odds'
        return f'1:{round(r, 2)} odds'`

**Comment by ellekdev** [comment]
Hi @GAMPR , thanks so much for  using `PiedPoker` and for the very kind words 😃 It makes me happy to hear that you enjoy this as much as I do! And thank you for providing this detailed bug analysis! Using your examples, I was able to reproduce the bug. I have gone ahead and fixed this `ZeroDivisionError` in the latest release, which is `1.1.1`.

I have also added more unit tests to assert around this functionality and ensure that this behavior will not result in this error. 

I will mark this as closed for now, but feel free to reopen or raise another issue if you encounter any other bugs!

Best,
Ellek
