### ISSUE TITLE
Deck doesn't check that cards must be unique

### ISSUE THREAD

**Issue by raphaelvdumas** [elleklinton/PiedPoker#4]
Hello, thank for your library, it's very nice ! Having a lot of fun playing around with it :)

I would suggest implementing a verification that raises an error when two cards are equal in rank and suit (be it either from a player or community cards), since the probabilities are completely broke if it's not the case. I've tried simulating a round with 2 players and 5 community cards having the same pp.Card('ac'), the simulator didn't complain and outputed that a player would lose even though he also had 2 pp.Card('ac') in hand. 

Cheers,

**Comment by ellekdev** [comment]
Hi @raphaelvdumas, thanks so much for  using `PiedPoker` and reporting this bug! I have gone ahead and fixed this bug in the latest release (`1.1.1`).

Now, when duplicate cards are present, a `RuntimeException` will be thrown.

Please update Pied Poker to version `1.1.1` and that should fix the issue.

I will mark this as closed for now, but feel free to reopen if you still have any issues around this.

Thanks!
Ellek
